import * as THREE from 'three';
export const NPC_DATA = [
  { name: 'The Architect', color: new THREE.Color(0x00ffff), hexColor: '#00ffff', stationIndex: 0, visualType: 'blueprint',
    quote: 'The first multiverse metaverse game studio, redefining immersive gaming. Our worlds are more than just games\u2014they are living, breathing digital realms, where players, creators, and developers shape the future, get an education and earn a living.',
    features: [],
    sections: [
      { heading: 'THE FUTURE OF GAMING' },
      { subheading: 'Our Mission', bullets: [
        'We are building the future of gaming, where digital worlds are connected, interoperable, and truly owned by the players.',
        'Our goal is to create an ecosystem where developers, creators, and players thrive together.',
      ]},
      { subheading: 'Our Vision', bullets: [
        'A limitless, player-driven multiverse powered by Web3, AI, and Unreal Engine.',
        'Imagine a world where assets, characters, and progress move with you\u2014across games, platforms, and even entirely different metaverses.',
      ]},
      { subheading: 'Our Team', bullets: [
        'Ultra Kingdoms was founded by visionaries in gaming, blockchain, and AI\u2014a team of industry veterans dedicated to pushing the boundaries of what\u2019s possible.',
      ]},
      { platforms: ['Xbox', 'PlayStation', 'Steam', 'Mobile'] },
      { stats: [
        { value: 4.8, suffix: 'M', label: 'Interested Users - and growing daily', sublabel: 'Built by word of mouth' },
        { value: 15, suffix: '', label: 'Worlds Integrated', sublabel: 'Metaverse projects' },
        { value: 30, suffix: '+', label: 'million $ Invested', sublabel: 'Founder-funded & debt-free' },
        { value: 7, suffix: '', label: 'Patents Granted', sublabel: 'Globally recognized' },
      ]},
      { tagline: 'While others are still figuring it out, we built it.' },
    ] },
  { name: 'The Broker', color: new THREE.Color(0xffaa00), hexColor: '#ffaa00', stationIndex: 1, visualType: 'ticker',
    quote: 'Ultra Kingdoms is a platform built to be an interoperable Multiverse Metaverse ecosystem that addresses 7-layers of any true metaverse, and then we go further, providing a rich and engaging experience for all players.',
    features: [],
    sections: [
      { heading: 'THE SEVEN TRADITIONAL LAYERS' },
      { cards: [
        { title: 'Infrastructure', desc: 'Servers, compute, cloud, and rendering pipelines power the entire ecosystem.', icon: '\u2699' },
        { title: 'Networking', desc: 'Cross-realm data transport and seamless communication.', icon: '\u{1F310}' },
        { title: 'Identity & Ownership', desc: 'Unified player identity and transferable assets.', icon: '\u{1F511}' },
        { title: 'Economy', desc: 'Shared currency, cross-realm markets, supply/demand.', icon: '\u{1F4B0}' },
        { title: 'AI', desc: 'Adaptive NPCs, behavioral learning, procedural systems.', icon: '\u{1F916}' },
        { title: 'World', desc: 'Partner worlds, biomes, and interactive environments.', icon: '\u{1F30D}' },
        { title: 'Experience', desc: 'Gameplay, quests, social systems, and exploration.', icon: '\u{1F3AE}' },
      ], layout: 'honeycomb' },
      { heading: 'FIVE ADDITIONAL LAYERS' },
      { cards: [
        { title: 'Safety & Security', desc: 'Robust protection for players, data, and digital assets across all realms.', icon: '\u{1F6E1}' },
        { title: 'Utility & Well Being', desc: 'Tools and systems that promote player health, balance, and meaningful engagement.', icon: '\u2764' },
        { title: 'Creation & Customization', desc: 'Empowering players and creators to build, modify, and personalize their worlds.', icon: '\u{1F3A8}' },
        { title: 'Financial Responsibility & Reward', desc: 'Transparent, fair economic systems where effort and contribution are rewarded.', icon: '\u{1F4C8}' },
        { title: 'Interoperability & Openness', desc: 'Seamless connectivity between worlds, platforms, and ecosystems with open standards.', icon: '\u{1F517}' },
      ], layout: 'honeycomb' },
    ] },
  { name: 'The Warden', color: new THREE.Color(0xff0044), hexColor: '#ff0044', stationIndex: 2, visualType: 'combat',
    quote: 'The Warden guards the portals between worlds. Many have sought passage\u2014only the worthy are approved.',
    features: [],
    sections: [
      { heading: 'APPROVED PORTALS' },
      { subheading: 'The following partners have been granted passage into the multiverse', bullets: [] },
      { image: '/partnerlogos.png' },
      { heading: 'GLOBAL SECURITY FEATURES' },
      { subheading: 'These are just the beginning', bullets: [] },
      { cards: [
        { title: 'AI Language Control', desc: 'Self-learning AI that monitors and adapts to language across all realms in real-time.', icon: '\u{1F9E0}' },
        { title: 'Type & Voice Control', desc: 'Intelligent moderation of text and voice communications for a safe environment.', icon: '\u{1F399}' },
        { title: 'Child Safety', desc: 'Age verification and parental controls to protect young players across the multiverse.', icon: '\u{1F6E1}' },
        { title: 'Religious Controls', desc: 'Content filters aligned with personal beliefs so you only see what complies with your values.', icon: '\u{1F54C}' },
        { title: 'Financial Controls', desc: 'Spending limits, transaction oversight, and fraud protection built into every realm.', icon: '\u{1F512}' },
      ], layout: 'honeycomb' },
    ] },
  { name: 'The Navigator', color: new THREE.Color(0x4488ff), hexColor: '#4488ff', stationIndex: 3, visualType: 'portal',
    quote: 'Explore each of the Ultra Kingdoms worlds. The Navigator charts the paths between realms. follow our partners and dive deeper into the multiverse.',
    features: [],
    sections: [
      { heading: 'EXPLORE THE WORLDS' },
      { carousel: [
        { name: 'World 1', logo: '/p0.webp', url: 'https://ultrakingdoms.com' },
        { name: 'World 2', logo: '/p1.webp', url: 'https://ultrakingdoms.com' },
        { name: 'World 3', logo: '/p2.webp', url: 'https://ultrakingdoms.com' },
        { name: 'World 4', logo: '/p3.webp', url: 'https://ultrakingdoms.com' },
        { name: 'World 5', logo: '/p4.webp', url: 'https://ultrakingdoms.com' },
        { name: 'World 6', logo: '/p5.webp', url: 'https://ultrakingdoms.com' },
        { name: 'World 7', logo: '/p6.webp', url: 'https://ultrakingdoms.com' },
      ]},
    ] },
  { name: 'The Syndicate Boss', color: new THREE.Color(0xaa00ff), hexColor: '#aa00ff', stationIndex: 4, visualType: 'faction',
    quote: 'Ultra Kingdoms is the first platform uniting all open world metaverse projects under one INTEROPERABLE roof. We seamlessly blend Web2 and Web3, and we\u2019re already approved on Xbox, PlayStation, Steam, and mobile.',
    features: [],
    sections: [
      { heading: 'A FLAGSHIP EXPERIENCE' },
      { statement: 'A next-generation metaverse RPG, where players explore, build, and battle across interconnected worlds. Forge alliances, conquer territories, and leave your mark on the multiverse.' },
      { cards: [
        { title: 'Explore', desc: 'Traverse vast interconnected realms with unique biomes and secrets.', icon: '\u{1F30D}' },
        { title: 'Build', desc: 'Create structures, economies, and communities that persist.', icon: '\u{1F3D7}' },
        { title: 'Battle', desc: 'Engage in skill-based PvP and large-scale faction warfare.', icon: '\u2694' },
        { title: 'Trade', desc: 'Cross-realm economy driven by real supply and demand.', icon: '\u{1F4B0}' },
        { title: 'Unite', desc: 'Form alliances, build guilds, and shape the political landscape.', icon: '\u{1F91D}' },
        { title: 'Conquer', desc: 'Claim territories across dimensions and defend your legacy.', icon: '\u{1F451}' },
      ], layout: 'pyramid' },
    ] },
  { name: 'The Oracle', color: new THREE.Color(0x00ffaa), hexColor: '#00ffaa', stationIndex: 5, visualType: 'timeline',
    quote: 'Ultra Kingdoms Oracle delivers a guided path through the revolutionary multiverse experience, empowering players with seamless cross-world exploration, dynamic combat, rich social interaction, and persistent identity that truly belongs to them.',
    features: [],
    sections: [
      { heading: 'GAMEPLAY & PLATFORMS' },
      { cards: [
        { title: 'Portal-based Travel', desc: 'Effortlessly jump between distinct, immersive realms.', icon: '\u{1F300}' },
        { title: 'Continuous Progression', desc: 'Your skills and achievements evolve across all connected worlds.', icon: '\u{1F4C8}' },
        { title: 'Dynamic Combat', desc: 'Engage intelligent NPCs and challenging foes with adaptive systems.', icon: '\u2694' },
        { title: 'Unified Economy', desc: 'Access a single marketplace and shared resource system.', icon: '\u{1F4B0}' },
        { title: 'Social Hubs & Events', desc: 'Connect with friends and communities in vibrant shared spaces.', icon: '\u{1F465}' },
        { title: 'Customizable Identity', desc: 'Personalize your characters and items across the multiverse.', icon: '\u{1F3AD}' },
        { title: 'Epic Storylines', desc: 'Uncover relics, secrets, and intertwined narratives across worlds.', icon: '\u{1F4DC}' },
      ], layout: 'honeycomb' },
    ] },
  { name: 'Ultra Kingdoms', color: new THREE.Color(0xff8800), hexColor: '#ff8800', stationIndex: 6, visualType: 'timeline',
    quote: '', features: [] },
];
